[package]
name = "merlin_module"
version = "0.1.0"
edition = "2021"
description = "Developer crate for writing Merlin kernel modules."
license = "MPL-2.0"

[dependencies]

[features]
default = []

[lib]
crate-type = ["rlib"]
